// GENERATED by scripts/gen_map_assets.py from
// data/static/custom_maps.json. Do not edit by hand — regenerate.
//
// Workshop/modded maps the operator declared bounds for. The reader
// already reads that JSON and attaches a layer block, so a recording
// made since then draws without this; the copy is here for the ones
// made before it, and so the landing page can name the thumbnail.
import type { FallbackMap } from "./mapFallbackData";

export const CUSTOM_MAPS: ReadonlyMap<string, FallbackMap> = new Map([
  ["Hrodna Border", { texture: "HrodnaBorder", topLeft: { x: -201579.5625, y: -201531.25 }, bottomRight: { x: 201620.46875, y: 201665.890625 } }],
]);
