#!/usr/bin/env python3
"""Build the frontend's map assets: minimap thumbnails + the modded-map table.

Two things the browser needs and cannot fetch for itself:

**Thumbnails.** The full sqmaps are 2.5-6.4 MB each — fine for the replay
canvas, which loads one, ruinous for the landing grid, which shows six. This
writes a small square copy of every map either table can name.

**The modded-map table.** `data/static/custom_maps.json` is the operator's
hand-written bounds for workshop maps; the reader uses it directly, but it
sits outside frontend/ and CONTRIBUTING.md's container build mounts only
frontend/ — so it has to be copied in as TypeScript to reach the bundle.

    python3 scripts/gen_map_assets.py     # needs Pillow

Outputs land in frontend/src/, not frontend/public/: the backend serves the
SPA and its `/assets/` build output and 404s anything else, so both have to
go through the bundler.

Run it by hand after editing custom_maps.json, adding a map to sqmaps/, or
regenerating mapFallbackData.ts — then rebuild the frontend and commit both.
It is deliberately NOT wired into `npm run build`, which runs in a node image
that has neither this script nor python3.
"""
import json
import re
import sys
from pathlib import Path
from typing import Any

from PIL import Image

SIZE = 400          # square; the landing grid crops it to 16:9 with object-fit
QUALITY = 72

ROOT = Path(__file__).resolve().parent.parent
SQMAPS = ROOT / "sqmaps"
CUSTOM_JSON = ROOT / "data" / "static" / "custom_maps.json"
TABLE = ROOT / "frontend" / "src" / "canvas" / "mapFallbackData.ts"
OUT_THUMBS = ROOT / "frontend" / "src" / "assets" / "thumbs"
OUT_CUSTOM = ROOT / "frontend" / "src" / "canvas" / "mapCustomData.ts"

EXTS = {".webp", ".png", ".jpg", ".jpeg"}
TEXTURE_RE = re.compile(r"^[A-Za-z0-9_]+$")


def corner(v: Any) -> dict[str, float] | None:
    if not isinstance(v, dict):
        return None
    out = {}
    for k in ("x", "y"):
        n = v.get(k)
        if isinstance(n, bool) or not isinstance(n, (int, float)):
            return None
        out[k] = float(n)
    return out


def custom_maps() -> dict[str, dict[str, Any]]:
    """Validated custom_maps.json entries. Mirrors metadata.py's `_custom_entry`
    — a half-written entry renders worse than no entry, so it is dropped."""
    if not CUSTOM_JSON.is_file():
        return {}
    raw = json.loads(CUSTOM_JSON.read_text())
    if not isinstance(raw, dict):
        print(f"{CUSTOM_JSON}: not an object — ignoring", file=sys.stderr)
        return {}
    out: dict[str, dict[str, Any]] = {}
    for key, entry in raw.items():
        texture = entry.get("texture") if isinstance(entry, dict) else None
        tl, br = (corner(entry.get("topLeft")), corner(entry.get("bottomRight"))) \
            if isinstance(entry, dict) else (None, None)
        if not isinstance(texture, str) or not TEXTURE_RE.match(texture) \
                or tl is None or br is None:
            print(f"custom_maps: ignoring {key!r} — needs a bare `texture` name "
                  f"and numeric topLeft/bottomRight corners", file=sys.stderr)
            continue
        out[key] = {"texture": texture, "topLeft": tl, "bottomRight": br}
    return out


def write_custom_ts(maps: dict[str, dict[str, Any]]) -> None:
    def pt(p: dict[str, float]) -> str:
        return "{ x: %s, y: %s }" % (p["x"], p["y"])
    rows = "".join(
        '  ["%s", { texture: "%s", topLeft: %s, bottomRight: %s }],\n'
        % (k, v["texture"], pt(v["topLeft"]), pt(v["bottomRight"]))
        for k, v in maps.items())
    OUT_CUSTOM.write_text(
        "// GENERATED by scripts/gen_map_assets.py from\n"
        "// data/static/custom_maps.json. Do not edit by hand — regenerate.\n"
        "//\n"
        "// Workshop/modded maps the operator declared bounds for. The reader\n"
        "// already reads that JSON and attaches a layer block, so a recording\n"
        "// made since then draws without this; the copy is here for the ones\n"
        "// made before it, and so the landing page can name the thumbnail.\n"
        'import type { FallbackMap } from "./mapFallbackData";\n\n'
        "export const CUSTOM_MAPS: ReadonlyMap<string, FallbackMap> = new Map([\n"
        f"{rows}]);\n")


def sources() -> dict[str, Path]:
    """Image files in sqmaps/, keyed by every stem spelling we match on."""
    by_stem: dict[str, Path] = {}
    for f in sorted(SQMAPS.iterdir()):
        if not f.is_file() or f.suffix.lower() not in EXTS:
            continue
        stem = f.stem.lower()
        by_stem.setdefault(stem, f)
        by_stem.setdefault(stem.replace("_", ""), f)
    return by_stem


def main() -> int:
    if not SQMAPS.is_dir():
        print(f"no sqmaps directory at {SQMAPS}", file=sys.stderr)
        return 1
    stock = sorted(set(re.findall(r'texture:\s*"([^"]+)"', TABLE.read_text())))
    if not stock:
        print(f"no textures found in {TABLE}", file=sys.stderr)
        return 1

    custom = custom_maps()
    write_custom_ts(custom)
    print(f"{OUT_CUSTOM.relative_to(ROOT)}: {len(custom)} modded map(s)")

    by_stem = sources()
    OUT_THUMBS.mkdir(parents=True, exist_ok=True)
    missing = []
    for t in sorted(set(stock) | {v["texture"] for v in custom.values()}):
        # Metadata textures carry Squad's asset decoration; the shipped files
        # mostly do not. Try the name, then without that suffix, then with the
        # underscores dropped (foolsroad.webp from Fools_Road).
        stem = re.sub(r"_(fmodel|Minimap)$", "", t, flags=re.I).lower()
        src = by_stem.get(t.lower()) or by_stem.get(stem) \
            or by_stem.get(stem.replace("_", ""))
        if src is None:
            missing.append(t)
            continue
        im = Image.open(src).convert("RGB")
        im.thumbnail((SIZE, SIZE), Image.LANCZOS)
        dst = OUT_THUMBS / f"{t}.webp"
        im.save(dst, "WEBP", quality=QUALITY, method=6)
        print(f"{t:<24} {src.name:<22} {dst.stat().st_size / 1024:6.1f} KB")
    if missing:
        print(f"\nno sqmaps file for: {', '.join(missing)}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
